### ISSUE TITLE
Form Product

### ISSUE THREAD

**Issue by Zchule** [Zchule/Preventa2#3]
Mostrar variables por defecto en los option de ion-select del formulario de registro de Producto como ser las de type="Alimentos", categories="Detergente en Barra", mark="Omo".

**Comment by nicobytes** [comment]
![screen shot 2017-06-06 at 2 58 24 am](https://cloud.githubusercontent.com/assets/7611944/26817310/1045daa6-4a64-11e7-9ff4-4ead3be9f86e.png)
